###
### Создание команды

POST http://localhost:8080/api/teams/
Content-Type: application/json

{
  "name": "teamB"
}

###
###Получение списка команд
GET http://localhost:8080/api/teams/

###
###Добавление работника в команду
POST http://localhost:8080/api/teams/6/employees/4/add


